FROM python:3.8-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install rasa-sdk==3.6.2 psycopg2-binary python-dotenv

COPY actions/ ./actions/

EXPOSE 5055

CMD ["python", "-m", "rasa_sdk", "--actions", "actions", "--port", "5055"]